package Parsing.ParsedTokens;

public enum ParsedTokenType {
    VALUE,
    BLOCK,
    STATEMENT,
    FUNCTION_DEFINITION,
    UNARY_OPERATION,
    BINARY_OPERATION,
    CONDITIONAL,
    FUNCTION_ARGS,
    ASSIGNMENT,
    UNKNOWN_OPERATION,
    CLASS_DEFINITION,
    TRY_STATEMENT,
    EXCEPT_STATEMENT,
    FINALLY_STATEMENT
}
