package Parsing.ParsedTokens;

public enum ParsedTokenType {
    INT,
    FLOAT,
    BLOCK,
    STATEMENT,
    FUNCTION_DEFINITION,
    UNARY_OPERATION,
    BINARY_OPERATION,
    VARIABLE,
    CONDITIONAL,
    FUNCTION_CALL,
    ASSIGNMENT,
    UNPARSED,
    STRING,
    LIST,
    MEMBERSHIP_FUNCTION_CALL,
    MEMBERSHIP_VARIABLE,
    CLASS_DEFINITION
}
